### PR TITLE
Make 'merge' to 'pull'

### PR DESCRIPTION
**Pull request by darkdarcool**
It's a proper term for `pull request`, not `merge request`!

### CODE REVIEW

**Comment by iop3** [comment]
im pretty sure codelongandprosper90 will not respond.

**Comment by darkdarcool** [comment]
Ok, but if he does, it's here!

**Comment by iop3** [comment]
lol yup

**Comment by darkdarcool** [comment]
eh. If he sees it, he'l open it.

**Comment by iop3** [comment]
lol ok

**Pull request closed without merging**
